/*
https://adventofcode.com/2016/day/6
--- Day 6: Signals and Noise ---
Something is jamming your communications with Santa. Fortunately, your signal is only partially jammed, and protocol in situations like this is to switch to a simple repetition code to get the message through.

In this model, the same message is sent repeatedly. You've recorded the repeating message signal (your puzzle input), but the data seems quite corrupted - almost too badly to recover. Almost.

All you need to do is figure out which character is most frequent for each position. For example, suppose you had recorded the following messages:
*/
var testInput = [
"eedadn",
"drvtee",
"eandsr",
"raavrd",
"atevrs",
"tsrnev",
"sdttsa",
"rasrtv",
"nssdts",
"ntnada",
"svetve",
"tesnvt",
"vntsnd",
"vrdear",
"dvrsen",
"enarar"];
/*
The most common character in the first column is e; in the second, a; in the third, s, and so on. Combining these characters returns the error-corrected message, easter.

Given the recording in your puzzle input, what is the error-corrected version of the message being sent?

https://adventofcode.com/2016/day/6/input
*/

function mostFreq(letterFreq) {
  var entries = Array.from(letterFreq);
  entries.sort(function(a, b) {
    if (a[1] < b[1]) {
      return 1;
    }
    if (a[1] > b[1]) {
      return -1; // highest frequency first
    }
    return a[0].localeCompare(b[0]);
  });
  return entries[0][0];
}
var testFreq = new Map();
testFreq.set("b", 3);
testFreq.set("a", 3);
testFreq.set("d", 4);
console.assert(mostFreq(testFreq) == "d");

function commonMessage(messages, freqEvaluator) {
  var letterFreqs = [];
  for (var i = 0; i < messages[0].length; i++) {
    letterFreqs[i] = new Map();
  }
  for (let message of messages) {
    for (var i = 0; i < message.length; i++) {
      let c = message[i];
      if (c < 'a' || c > 'z') {
        continue;
      }
      if (letterFreqs[i].has(c)) {
        letterFreqs[i].set(c, letterFreqs[i].get(c) + 1);
      } else {
        letterFreqs[i].set(c, 1);
      }
    }
  }
  var result = "";
  for (var i = 0; i < messages[0].length; i++) {
    result += freqEvaluator(letterFreqs[i]);
  }
  return result;
}
console.assert(commonMessage(["teat", "west", "tase"], mostFreq) == "test");
console.assert(commonMessage(testInput, mostFreq) == "easter");

var input = [
"blrqqadw",
"hxwteava",
"xtzzneor",
"ufydaiyx",
"hhvcoozu",
"nbbvuvmd",
"usvdcalw",
"rpntrbyo",
"kgjholvo",
"nlohafzu",
"gxmifiuy",
"xndolmhm",
"zmtsfmtq",
"wkdzmogx",
"aogqflji",
"uphmjtnl",
"jkqognlw",
"mdzsbrij",
"zyxolasw",
"kvdyikgy",
"xpxgmuqq",
"viuoqyap",
"simgbmca",
"qxcjewnz",
"ivwoedjr",
"mlmzozlr",
"jmyallmm",
"oeecmjte",
"miuvzeww",
"qtfsiigb",
"lstgpdfp",
"pevoamxy",
"mjtpbedv",
"ugbasbgg",
"idcnuhtx",
"wwhcrxdr",
"prrugmrq",
"npoiywvw",
"zpkohigv",
"wngoczfk",
"gxnmxano",
"cbacsmte",
"meclajtf",
"zhztflqy",
"grqqlecu",
"qjbzsptn",
"ebagoidi",
"egegrnyh",
"jccwkqle",
"ikkwrzqt",
"nedkjwhf",
"vildwwrp",
"ugrejotn",
"kdajfbqw",
"gyiwhxpd",
"eemhkuwh",
"jvfhoiqi",
"wsgyaiip",
"jzjvagvv",
"lqupczes",
"fetfptqt",
"msmlbgcf",
"iukfpgrm",
"ctymfjpj",
"rbrpmkvx",
"glooxgap",
"scctgiai",
"lakkjuyk",
"gaekimfl",
"bhfaybki",
"qaiazzpf",
"dwqkvsee",
"fuhbygkt",
"zhkggelc",
"haigokzn",
"jpuangaj",
"tpunltos",
"izqxnhhd",
"oeyxnqkn",
"vzvelmik",
"ddnaozap",
"mdlhkdlu",
"oglyexnm",
"mcgxswpe",
"jzkjknxc",
"gfqnuhfs",
"ztnxzwng",
"bnuxixlk",
"vmumdwec",
"kuxxbcbv",
"vdcfhyso",
"qtdesxqr",
"qciljohn",
"qqlluqzz",
"njhvvqbw",
"knakngrj",
"pradgsbt",
"koffjwwy",
"tvrkgjql",
"mqtxerte",
"smigupym",
"bxxvoskx",
"jerbindg",
"snlgnowp",
"qsuxtdsu",
"fnpexyoa",
"ffwifdad",
"mvgrpczm",
"oxszzrsb",
"pxefzlch",
"mcgbeauh",
"neseoapm",
"iwnulsrv",
"zhinoifi",
"lfmjmmtk",
"fsxcqurn",
"gmkkhfuh",
"nuqeimxo",
"uvjdgkdo",
"ohtmvkcu",
"albuiptc",
"piaihrgr",
"fjviblws",
"qotlvddl",
"gchijkjr",
"azzrnqhy",
"xrynrbck",
"pdvkcekk",
"thscvzai",
"eoapfznw",
"hpgoissz",
"ifnesaoy",
"eniqycje",
"hmjmghcp",
"sfyrvbbi",
"tuxcoidt",
"icysmkcf",
"ycagvtls",
"dohqfcgc",
"taitvkzk",
"bblnroyh",
"grdklrua",
"qpijbooa",
"pcwtjacj",
"mrvxbefl",
"oodwrtvj",
"xosqbcie",
"zbquakff",
"ypwpamng",
"rpfbkssq",
"fctgmcav",
"hdtcdfcf",
"ctboapkz",
"qypakerm",
"vebdtsmq",
"cyxqtbtt",
"dcnpkmnu",
"hnjppwfo",
"gqmfdahb",
"hxiqcrbe",
"rpxazkak",
"nmtraoky",
"sisqtogo",
"oycwooev",
"lmmitjey",
"rytzptco",
"waatgjdu",
"khsuxyse",
"cxjltfxn",
"eedsmcld",
"fngdicwe",
"lkomchdq",
"ulvabpoz",
"oyhjvimr",
"dpyexiwi",
"wjfzkbbv",
"ihohnaxx",
"ajxfefrv",
"bplrrpcz",
"rtamodoq",
"slwrcibk",
"sgwdtumz",
"vlemhplz",
"dnpkqvad",
"ytolejsa",
"ojevrxsc",
"bgbmnvyv",
"lmrousup",
"yyubvohm",
"bqaqltmt",
"vfbzzthz",
"ylehjmop",
"exddqqwo",
"xqfxejzq",
"myyuypku",
"zyvmvbla",
"cnpquvbp",
"yaxdddeq",
"cnrjqdra",
"lwphgfgf",
"zqdbcnmn",
"qelivdwx",
"wpnwomgu",
"xzephbpa",
"yghrabgr",
"pnjsyhth",
"okdznczw",
"urwcwwfm",
"hjrsrrzk",
"foklmzqs",
"mjldwaun",
"dabalbmb",
"jmtqvwst",
"uhtzixah",
"blclhmjf",
"wilsnjwb",
"qeeriszr",
"vbfagerv",
"afegxkkh",
"zwzausdd",
"ysfgzvbw",
"ymjlmnmz",
"rnrbxnij",
"ihvhqtvk",
"ofwrugbp",
"ontvlhfu",
"sfjgpqpx",
"oyzkaiyl",
"xfmvkfkh",
"pqpeeptl",
"jdyueahx",
"plghatyl",
"yrdizope",
"lrurgkqw",
"xdqtlmww",
"dkaiotxb",
"iegjcmln",
"iupoupxa",
"zrepcilx",
"tpewzoxi",
"munsmbpj",
"fvhsucvb",
"rlwchfml",
"kcmlbubj",
"jnhurapr",
"dflwxeii",
"wtypbujm",
"jivypmpr",
"argvlhnz",
"acyvvplf",
"naqafzfw",
"ngepfsju",
"xfpuwtji",
"pqgkxbmj",
"oeygjbxs",
"evoydkqq",
"nhuoohdi",
"wrznguek",
"ssirmkbq",
"ackhglvh",
"egszqozo",
"rhnhhxul",
"mqabqvun",
"yunlcuvd",
"zklsneau",
"itanrdqb",
"pvxbkwoc",
"rqbqjyuv",
"ioxjpvqd",
"pzkgsdej",
"yklripsi",
"iohazhoh",
"umxxpdaw",
"czfnfgxt",
"xaxvkjjc",
"qhgvdvaa",
"iobwhxjq",
"jwfwqqjs",
"cbrfgjpp",
"conpdlzv",
"wbcmssue",
"gyqkseid",
"ozrzahxt",
"rzowboce",
"lhntmyie",
"tlrcktzc",
"lxmzpvku",
"ckliqrdt",
"qlmalosg",
"ovvyxrnr",
"gctjwzrl",
"ooqvxzac",
"dbdqzzly",
"fpsjzuxx",
"njndzgel",
"hjfqofhh",
"txhcpktf",
"otceqnmc",
"dduyepiz",
"bsxdbzgs",
"zklbicun",
"rstnuwtg",
"tasiqsbs",
"wewnwuyn",
"zvgkuxxp",
"nxcmlrmx",
"mizqhlnv",
"xyxzfeca",
"qkeuwzgi",
"ajnzmfks",
"ejszlxyc",
"xzfggxpd",
"jbooydts",
"eisoqvuo",
"hdfpevns",
"alybbyrb",
"yvpylcnz",
"tdpcycrv",
"kwptuqyw",
"ncobyufk",
"fclvkbek",
"tgnfcfup",
"vbcuaudl",
"hublkdvy",
"aoetzcyl",
"fsiuwhbi",
"eyolgmxh",
"siptvnjn",
"shvycepr",
"ntrwmime",
"dbdnbfyt",
"bwluchce",
"uigenqhy",
"krxdyhap",
"avycqglh",
"gguniqpm",
"wcwzelyd",
"wzurdris",
"rmhstxuj",
"vuaozvvq",
"bsdgqrpx",
"twnvkunt",
"nqgqtugs",
"vzkvghwg",
"ypceflob",
"dsyzunmb",
"kvhacqqr",
"ozlfwkjl",
"pyznytxd",
"ykdkbfgf",
"eajwdyia",
"bhkxsxcc",
"vytpdoop",
"ibpypdrh",
"dkkjnwng",
"lxwkkldf",
"nbtckkoy",
"qtjyffvl",
"sbitpceb",
"sxmhbcuy",
"zorovlxd",
"bazreact",
"cwzggemu",
"uowhquji",
"eijszbmy",
"aarneovu",
"grhvjqyo",
"fzheiyvq",
"nzsdrlli",
"wfsdwsok",
"wrqjuygq",
"ggpffnri",
"wkycrfjm",
"drksyjxn",
"smuhwcxa",
"iabdvvyj",
"esidunjn",
"decnfzwl",
"ysihdzkf",
"zokmsjgk",
"pxuddjdo",
"uemyoegc",
"glqycmsw",
"fvfkqzdu",
"mhotjpqc",
"pfyuopbx",
"tibutsqb",
"krzcqnkv",
"djqpmsmb",
"vbufrshp",
"mmzsrikm",
"zkjbrtoo",
"uopielbd",
"jmketnly",
"raomwphg",
"uwocphkf",
"lvktwagm",
"lqmorzgf",
"rihrgrdp",
"cnbuplfg",
"hwfjvxcj",
"sfgptuic",
"ixkimxsx",
"kfpicnix",
"tvpybbrf",
"navehxpr",
"rwbcttbq",
"obqcxwjd",
"fuiskmfg",
"xcvfxoeh",
"tsmaaoyx",
"qjhiyeex",
"qwfxiyxq",
"ctkyxatm",
"hyxhsvmy",
"puknicfi",
"hbwzmyks",
"uczqlycu",
"wkywzgqs",
"kzfehffd",
"aoooehdc",
"lnijvgrg",
"aedbnxzk",
"lusvnger",
"ltpbpgiq",
"aypxjgwo",
"lgejygmw",
"auqexwja",
"fwszagnq",
"aiafpduf",
"lyltmest",
"agtasqwl",
"fqrlliiw",
"udarpyjv",
"kxotyded",
"aodevwdt",
"lmmfarbx",
"snjwogeo",
"ehfmpymn",
"yahfaxeo",
"xudbdnog",
"rrkxhhsy",
"hdxadfck",
"dmnujkng",
"cujvjtry",
"srwxylvi",
"dwohbywb",
"cvspfupf",
"czvvjhfw",
"wvyjwtzz",
"vfooqywj",
"bmulxlpz",
"hbukjylo",
"bdhsvgdg",
"vnrrqyue",
"hjveswxf",
"yxgzdjwn",
"byonsarh",
"edbmtqyz",
"owvunnfp",
"wfqqsuyj",
"cwckbkwt",
"plesmdky",
"pzatdacm",
"nqfyxhij",
"jjwqitsc",
"tejffykk",
"yllyznoo",
"kkqhuqlc",
"hxchsqos",
"buvmceha",
"kbzymzrl",
"kiemcigv",
"txmjfujf",
"vfnystic",
"kvaiybnq",
"ztrwxszz",
"wiyawlfm",
"sgedycpx",
"isafnieb",
"bpspuqvx",
"fqjtxrtb",
"bgjdrvhb",
"mnsbgbhe",
"jpsqcfzz",
"fpumugea",
"qqutezwg",
"eoabntsw",
"tupqchzt",
"ezwjasja",
"rsguwrqg",
"cqzcijqd",
"rhxlhksr",
"vcwlknrc",
"eiqbcafb",
"lwzbrrtr",
"aomiovcj",
"ujxshcar",
"fbpjehma",
"bgdphfwg",
"iukvlxvq",
"ptawvjzy",
"styyqrqd",
"itobtfvm",
"yqnpsyha",
"vkwfaykp",
"zwpoxkzx",
"uqwasoht",
"tkgfmnvj",
"xkilydvt",
"xlmkpdaz",
"xfvukjte",
"yyzpwped",
"xzxwnrlm",
"ausmhunn",
"qgiiljhq",
"njqhxprl",
"fgfxiphp",
"kkzjpuur",
"dcqixesl",
"tthldwgg",
"nkjxnttn",
"cjtiiltj",
"drlzddsv",
"xxluiael",
"kjjsewia",
"danhtpxa",
"edexzcqw",
"mrqewvuh",
"opwtwbbt",
"rdbsaeke",
"viistwnj",
"llcndvsm",
"jeejjqyb",
"hstekias",
"gmswtskg",
"qhdktszo",
"ptbryiff",
"jrtlgbag",
"gjbbbfnu",
"uirwdwzh",
"esmntxej",
"vdcmrenk",
"tagtsvaz",
"hnewrron",
"zydwkvuh",
"zscfhzxk",
"sazgunom",
"gqcxdowc",
"twmxtniu",
"wfblhfiv",
"barpdrob",
"jwjrnqhv",
"xvnysjvz",
"jvsftvqs",
"jivuhphv",
"grbezkpe",
"xuolyqis",
"smuxlqpu",
"rticwcrh",
"huzyzxul",
"pgqawldg",
"mdcgejab",
"rlrgwpfo",
"uqhvyglu",
"csinjsjy",
"ydorfrud",
"gmcnjnbr",
"qzvizjbt",
"vejkuvii",
"uhfrombz",
"clgrjlys"];
console.log(commonMessage(input, mostFreq));

/*
--- Part Two ---
Of course, that would be the message - if you hadn't agreed to use a modified repetition code instead.

In this modified code, the sender instead transmits what looks like random data, but for each character, the character they actually want to send is slightly less likely than the others. Even after signal-jamming noise, you can look at the letter distributions in each column and choose the least common letter to reconstruct the original message.

In the above example, the least common character in the first column is a; in the second, d, and so on. Repeating this process for the remaining characters produces the original message, advent.

Given the recording in your puzzle input and this new decoding methodology, what is the original message that Santa is trying to send?
*/
function leastFreq(letterFreq) {
  var entries = Array.from(letterFreq);
  entries.sort(function(a, b) {
    if (a[1] < b[1]) {
      return -1; // lowest frequency first
    }
    if (a[1] > b[1]) {
      return 1;
    }
    return a[0].localeCompare(b[0]);
  });
  return entries[0][0];
}
console.assert(commonMessage(testInput, leastFreq) == "advent");
console.log(commonMessage(input, leastFreq));
